export const stats = [
  {
    id: 1,
    name: "Lemma",
    value: "Lemma",
    tooltip: "Uninflected word form",
    type: "checkbox",
  },
  {
    id: 2,
    name: "Most common part of speech",
    value: "mcPoS",
    type: "checkbox-group",
  },
  {
    id: 3,
    name: "Number of Letters",
    value: "numberOfLetters",
    type: "slider",
    minValue: 0,
    maxValue: 50,
    step: 5,
    skipWords: true,
  },
  {
    id: 4,
    name: "Raw frequency",
    value: "Count",
    tooltip:
      "Number of times the word is encountered in the selected age range",
    type: "slider",
    minValue: 0,
    maxValue: 1000,
    step: 50,
  },
  {
    id: 5,
    name: "Zipf frequency",
    value: "Zipf_freq",
    tooltip: "Standardised frequency metric in the selected age range",
    type: "slider",
    minValue: 1,
    maxValue: 8,
    step: 1,
  },
  {
    id: 6,
    name: "Book raw count",
    value: "CD_book_count_raw",
    tooltip:
      "Number of books in the selected age range the word is encountered in",
    type: "slider",
    minValue: 0,
    maxValue: 500,
    step: 25,
  },
  {
    id: 7,
    name: "Book percentage",
    value: "CD_book_perc_raw",
    tooltip:
      "Percentage of books in the selected age range the word is encountered in",
    type: "slider",
    minValue: 0,
    maxValue: 100,
    step: 10,
  },
  {
    id: 8,
    name: "Raw frequency in CBeebies TV programmes (ages 0-6)",
    value: "CBeebies_raw",
    type: "slider",
    minValue: 0,
    maxValue: 100,
    step: 5,
  },
  {
    id: 9,
    name: "Zipf frequency in CBeebies TV programmes (ages 0-6)",
    value: "CBeebies_log",
    type: "slider",
    minValue: 1,
    maxValue: 8,
    step: 1,
  },
  {
    id: 10,
    name: "Raw frequency in CBBC TV programmes (ages 6-12)",
    value: "CBBC_raw",
    type: "slider",
    minValue: 0,
    maxValue: 100,
    step: 5,
  },
  {
    id: 11,
    name: "Zipf frequency in CBBC TV programmes (ages 6-12)",
    value: "CBBC_log",
    type: "slider",
    minValue: 1,
    maxValue: 8,
    step: 1,
  },
  {
    id: 12,
    name: "Raw frequency in TV programmes (all ages)",
    value: "SubtlexUK_raw",
    type: "slider",
    minValue: 0,
    maxValue: 100,
    step: 5,
  },
  {
    id: 13,
    name: "Zipf frequency in TV programmes (all ages)",
    value: "SubtlexUK_log",
    type: "slider",
    minValue: 1,
    maxValue: 8,
    step: 1,
  },
];

export const mcpos = [
  { id: 1, name: "Noun", value: "NN" },
  { id: 2, name: "Verb", value: "VB" },
  { id: 3, name: "Adjective", value: "JJ" },
  { id: 4, name: "Adverb", value: "RB" },
];
