export const stats = [
  {
    id: "Lemma",
    name: "Lemma",
    value: "Lemma",
    tooltip: "Uninflected word form",
    type: "checkbox",
  },
  {
    id: 2,
    name: "Most common part of speech",
    value: "mcPoS",
    tooltip:
      "Part of speech the word is used in most frequently. Please refer to the READ ME tab for information on what each abbreviation stands for",
    type: "checkbox-group",
  },
  {
    id: "LetterCount",
    name: "Number of letters",
    value: "LetterCount",
    type: "slider",
    minValue: 1,
    maxValue: 58,
    step: 1,
    marks: [
      { value: 1, label: "1" },
      { value: 12, label: "12" },
      { value: 24, label: "24" },
      { value: 36, label: "36" },
      { value: 48, label: "48" },
      { value: 58, label: "58" },
    ],
    skipWords: true,
  },
  {
    id: "Count",
    name: "Raw frequency",
    value: "Count",
    tooltip:
      "Number of times the word is encountered in the selected age range",
    type: "slider",
    minValue: 0,
    maxValue: 3671782,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 1000000, label: "1M" },
      { value: 2000000, label: "2M" },
      { value: 3000000, label: "3M" },
      { value: 3671782, label: "3,671,782" },
    ],
  },
  {
    id: "Zipf_freq",
    name: "Zipf frequency",
    value: "Zipf_freq",
    tooltip: "Standardised frequency metric in the selected age range",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 0.1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
  {
    id: "CD_book_perc_raw",
    name: "Book proportion",
    value: "CD_book_perc_raw",
    tooltip:
      "Proportion of books in the selected age range in which the word is encountered",
    type: "slider",
    minValue: 0,
    maxValue: 1,
    step: 0.01,
    marks: [
      { value: 0, label: "0" },
      { value: 0.25, label: "0.25" },
      { value: 0.5, label: "0.5" },
      { value: 0.75, label: "0.75" },
      { value: 1, label: "1" },
    ],
  },
  {
    id: "CBeebies_raw",
    name: "Raw frequency in CBeebies TV programmes (ages 0-6)",
    value: "CBeebies_raw",
    type: "slider",
    minValue: 0,
    maxValue: 186232,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 50000, label: "50k" },
      { value: 100000, label: "100k" },
      { value: 150000, label: "150k" },
      { value: 186232, label: "186,232" },
    ],
  },
  {
    id: "CBeebies_log",
    name: "Zipf frequency in CBeebies TV programmes (ages 0-6)",
    value: "CBeebies_log",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 0.1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
  {
    id: "CBBC_raw",
    name: "Raw frequency in CBBC TV programmes (ages 6-12)",
    value: "CBBC_raw",
    type: "slider",
    minValue: 0,
    maxValue: 512056,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 100000, label: "100k" },
      { value: 200000, label: "200k" },
      { value: 300000, label: "300k" },
      { value: 400000, label: "400k" },
      { value: 512056, label: "512,056" },
    ],
  },
  {
    id: "CBBC_log",
    name: "Zipf frequency in CBBC TV programmes (ages 6-12)",
    value: "CBBC_log",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 0.1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
  {
    id: "SubtlexUK_raw",
    name: "Raw frequency in TV programmes (all ages)",
    value: "SubtlexUK_raw",
    type: "slider",
    minValue: 0,
    maxValue: 9418422,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 2000000, label: "2M" },
      { value: 4000000, label: "4M" },
      { value: 6000000, label: "6M" },
      { value: 8000000, label: "8M" },
      { value: 9418422, label: "9,418,422" },
    ],
  },
  {
    id: "SubtlexUK_log",
    name: "Zipf frequency in TV programmes (all ages)",
    value: "SubtlexUK_log",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 0.1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
];

export const mcpos = [
  { id: 1, name: "Noun", value: "NN", codes: ["NN", "NNS"] },
  { id: 2, name: "Verb", value: "VB", codes: ["VB"] },
  { id: 3, name: "Adjective", value: "JJ", codes: ["JJ"] },
  { id: 4, name: "Adverb", value: "RB", codes: ["RB", "RBR", "RBS", "WRB"] },
  { id: 5, name: "Pronoun", value: "PRP", codes: ["PRP", "PP$", "WP", "WP$"] },
  { id: 6, name: "Determiner", value: "DT", codes: ["DT", "PDT"] },
  { id: 7, name: "Preposition", value: "IN", codes: ["IN"] },
  { id: 8, name: "Conjunction", value: "CC", codes: ["CC"] },
];
