export const stats = [
  {
    id: 1,
    name: "Lemma",
    value: "Lemma",
    tooltip: "Uninflected word form",
    type: "checkbox",
  },
  {
    id: 2,
    name: "Most common part of speech",
    value: "mcPoS",
    tooltip:
      "Part of speech the word is used in most frequently. Please refer to the READ ME tab for information on what each abbreviation stands for",
    type: "checkbox-group",
  },
  {
    id: 3,
    name: "Number of letters",
    value: "numberOfLetters",
    type: "slider",
    minValue: 0,
    maxValue: 58,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 12, label: "12" },
      { value: 24, label: "24" },
      { value: 36, label: "36" },
      { value: 48, label: "48" },
      { value: 58, label: "58" },
    ],
    skipWords: true,
  },
  {
    id: 4,
    name: "Raw frequency",
    value: "Count",
    tooltip:
      "Number of times the word is encountered in the selected age range",
    type: "slider",
    minValue: 0,
    maxValue: 1200,
    step: 10,
    marks: [
      { value: 0, label: "0" },
      { value: 300, label: "300" },
      { value: 600, label: "600" },
      { value: 900, label: "900" },
      { value: 1200, label: "1200" },
    ],
  },
  {
    id: 5,
    name: "Zipf frequency",
    value: "Zipf_freq",
    tooltip: "Standardised frequency metric in the selected age range",
    type: "slider",
    minValue: 1,
    maxValue: 8,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
  {
    id: 6,
    name: "Book proportion",
    value: "CD_book_perc_raw",
    tooltip:
      "Proportion of books in the selected age range in which the word is encountered",
    type: "slider",
    minValue: 0,
    maxValue: 100,
    step: 5,
    marks: [
      { value: 0, label: "0" },
      { value: 25, label: "0.25" },
      { value: 50, label: "0.5" },
      { value: 75, label: "0.75" },
      { value: 100, label: "1" },
    ],
  },
  {
    id: 7,
    name: "Raw frequency in CBeebies TV programmes (ages 0-6)",
    value: "CBeebies_raw",
    type: "slider",
    minValue: 0,
    maxValue: 187000,
    step: 3740,
    marks: [
      { value: 0, label: "0" },
      { value: 50000, label: "50k" },
      { value: 100000, label: "100k" },
      { value: 150000, label: "150k" },
      { value: 187000, label: "187k" },
    ],
  },
  {
    id: 8,
    name: "Zipf frequency in CBeebies TV programmes (ages 0-6)",
    value: "CBeebies_log",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
  {
    id: 9,
    name: "Raw frequency in CBBC TV programmes (ages 6-12)",
    value: "CBBC_raw",
    type: "slider",
    minValue: 0,
    maxValue: 520000,
    step: 20000,
    marks: [
      { value: 0, label: "0" },
      { value: 100000, label: "100k" },
      { value: 200000, label: "200k" },
      { value: 300000, label: "300k" },
      { value: 400000, label: "400k" },
      { value: 520000, label: "520k" },
    ],
  },
  {
    id: 10,
    name: "Zipf frequency in CBBC TV programmes (ages 6-12)",
    value: "CBBC_log",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
  {
    id: 11,
    name: "Raw frequency in TV programmes (all ages)",
    value: "SubtlexUK_raw",
    type: "slider",
    minValue: 0,
    maxValue: 9420000,
    step: 98125,
    marks: [
      { value: 0, label: "0" },
      { value: 2000000, label: "2M" },
      { value: 4000000, label: "4M" },
      { value: 6000000, label: "6M" },
      { value: 8000000, label: "8M" },
      { value: 9420000, label: "9.4M" },
    ],
  },
  {
    id: 12,
    name: "Zipf frequency in TV programmes (all ages)",
    value: "SubtlexUK_log",
    type: "slider",
    minValue: 0,
    maxValue: 8,
    step: 1,
    marks: [
      { value: 0, label: "0" },
      { value: 2, label: "2" },
      { value: 4, label: "4" },
      { value: 6, label: "6" },
      { value: 8, label: "8" },
    ],
  },
];

export const mcpos = [
  { id: 1, name: "Noun", value: "NN" },
  { id: 2, name: "Verb", value: "VB" },
  { id: 3, name: "Adjective", value: "JJ" },
  { id: 4, name: "Adverb", value: "RB" },
];
